version: '1.0.{build}'

image: Visual Studio 2017

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: false
  
before_build:
- cd C:\projects\nowgua-net
- appveyor-retry nuget restore

platform: Any CPU
 
configuration: Release

build:
  project: nowguaClient.sln

  # MSBuild verbosity level
  verbosity: minimal


after_build:
- cd C:\projects\nowgua-net\nowguaClient\bin\Package
- ls
 
artifacts:
- path: 'projects\nowgua-net\nowguaClient\bin\Package\*.nupkg'
  name: NET-Package
  type: NuGetPackage

deploy:
- provider: Environment
  name: Nowgua-net
  on: 
    appveyor_repo_tag: false 


