version: '1.0.{build}'

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
    
image: Visual Studio 2017

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: false
  
before_build:
- cd C:\projects\nowgua-net
- appveyor-retry nuget restore

platform: Any CPU
 
configuration: Release

build:
  project: nowguaClient.sln

  # MSBuild verbosity level
  verbosity: minimal


 
artifacts:
- path: 'nowguaClient\bin\Package\*.nupkg'
  name: NET-Package
  type: NuGetPackage

deploy:
- provider: Environment
  name: nowgua-net
  on: 
    appveyor_repo_tag: true 

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
