version: '1.0.{build}'

nuget:
  account_feed: true
  project_feed: true
  
before_build:
- cd C:\nowgua\nowgua-net
- appveyor-retry nuget restore -v detailed

build:
  project: nowguaClient.sln      # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts

  # MSBuild verbosity level
  verbosity: detailed

test_script:
- cd C:\nowgua\nowgua-net
- dotnet.exe test "nowguaClientTest"

artifacts:
- path: '**\*.nupkg'
  name: NET-Package
  type: NuGetPackage

deploy:
- provider: Environment
  name: nowgua-net-nuget
  on: 
    appveyor_repo_tag: true 


notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false